name: i18n_extension
description: Translation and Internationalization (i18n) for Flutter. Easy to use for both large and small projects. Uses Dart extensions to reduce boilerplate.
version: 11.0.0-dev.1
# author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/i18n_extension
topics:
  - internationalization
  - localization
  - translation
  - i18n
  - extension

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  intl: ^0.18.0
  i18n_extension_core: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.9


