name: i18n_extension
description: Translation and Internationalization (i18n) for Flutter. Easy to use for both large and small projects. Uses Dart extensions to reduce boilerplate.
version: 10.0.1
homepage: https://github.com/marcglasberg/i18n_extension
# author: Marcelo Glasberg <marcglasberg@gmail.com>

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  sprintf: ^7.0.0
  args: ^2.4.2
  equatable: ^2.0.5
  intl: ^0.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.9


